// <auto-generated />
using System;
using CoursVia.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoursVia.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509191420_AddOnlineMiToKullanici")]
    partial class AddOnlineMiToKullanici
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoursVia.Models.AdminLog", b =>
                {
                    b.Property<int>("AdminLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminLogId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("IpAdresi")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("IslemTipId")
                        .HasColumnType("int");

                    b.HasKey("AdminLogId");

                    b.HasIndex("AdminId");

                    b.HasIndex("IslemTipId");

                    b.ToTable("AdminLog", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Bildirim", b =>
                {
                    b.Property<int>("BildirimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("BildirimTipId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OkunduMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("BildirimId");

                    b.HasIndex("BildirimTipId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Bildirimler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.BildirimTipi", b =>
                {
                    b.Property<int>("BildirimTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BildirimTipId"));

                    b.Property<string>("BildirimTipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BildirimTipId");

                    b.HasIndex("BildirimTipAdi")
                        .IsUnique();

                    b.ToTable("BildirimTipleri", (string)null);

                    b.HasData(
                        new
                        {
                            BildirimTipId = 1,
                            BildirimTipAdi = "Bilgilendirme"
                        },
                        new
                        {
                            BildirimTipId = 2,
                            BildirimTipAdi = "Uyarı"
                        },
                        new
                        {
                            BildirimTipId = 3,
                            BildirimTipAdi = "Hata"
                        });
                });

            modelBuilder.Entity("CoursVia.Models.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BolumId"));

                    b.Property<string>("BolumAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.HasKey("BolumId");

                    b.HasIndex("KursId", "BolumAdi")
                        .IsUnique();

                    b.HasIndex("KursId", "SiraNo")
                        .IsUnique();

                    b.ToTable("Bolumler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("BolumId")
                        .HasColumnType("int");

                    b.Property<string>("DersAdi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<bool>("SistemDersiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DersId");

                    b.HasIndex("BolumId");

                    b.HasIndex("KursId", "SiraNo")
                        .IsUnique();

                    b.ToTable("Dersler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.DersIlerlemesi", b =>
                {
                    b.Property<int>("DersIlerlemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DersIlerlemeId"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("KursKayitId")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.HasKey("DersIlerlemeId");

                    b.HasIndex("DersId");

                    b.HasIndex("KursKayitId", "DersId")
                        .IsUnique();

                    b.ToTable("DersIlerlemeleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.DersMateryali", b =>
                {
                    b.Property<int>("MateryalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateryalId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("MateryalTipId")
                        .HasColumnType("int");

                    b.Property<string>("MateryalUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("YuklenmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("MateryalId");

                    b.HasIndex("DersId");

                    b.HasIndex("MateryalTipId");

                    b.ToTable("DersMateryalleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Durum", b =>
                {
                    b.Property<int>("DurumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DurumId"));

                    b.Property<string>("DurumAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DurumId");

                    b.HasIndex("DurumAdi")
                        .IsUnique();

                    b.ToTable("Durumlar", (string)null);

                    b.HasData(
                        new
                        {
                            DurumId = 1,
                            DurumAdi = "Aktif"
                        },
                        new
                        {
                            DurumId = 2,
                            DurumAdi = "Pasif"
                        },
                        new
                        {
                            DurumId = 3,
                            DurumAdi = "Taslak"
                        },
                        new
                        {
                            DurumId = 4,
                            DurumAdi = "Onay Bekliyor"
                        },
                        new
                        {
                            DurumId = 5,
                            DurumAdi = "Onaylandı"
                        },
                        new
                        {
                            DurumId = 6,
                            DurumAdi = "Reddedildi"
                        },
                        new
                        {
                            DurumId = 7,
                            DurumAdi = "Düzeltme İsteniyor"
                        });
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenBransi", b =>
                {
                    b.Property<int>("EgitmenBransId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenBransId"));

                    b.Property<int>("EgitmenProfilId")
                        .HasColumnType("int");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.HasKey("EgitmenBransId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("EgitmenProfilId", "KategoriId")
                        .IsUnique();

                    b.ToTable("EgitmenBranslari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenOnayi", b =>
                {
                    b.Property<int>("EgitmenOnayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenOnayId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.HasKey("EgitmenOnayId");

                    b.HasIndex("AdminId");

                    b.HasIndex("DurumId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("EgitmenOnaylari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenProfili", b =>
                {
                    b.Property<int>("EgitmenProfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EgitmenProfilId"));

                    b.Property<string>("Biyografi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeneyimYili")
                        .HasColumnType("int");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("UzmanlikAlani")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EgitmenProfilId");

                    b.HasIndex("DurumId");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("EgitmenProfilleri", null, t =>
                        {
                            t.HasCheckConstraint("CK_EgitmenProfilleri_DeneyimYili", "[DeneyimYili] IS NULL OR [DeneyimYili] >= 0");
                        });
                });

            modelBuilder.Entity("CoursVia.Models.Favori", b =>
                {
                    b.Property<int>("FavoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriId"));

                    b.Property<DateTime>("EklenmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.HasKey("FavoriId");

                    b.HasIndex("KursId");

                    b.HasIndex("KullaniciId", "KursId")
                        .IsUnique();

                    b.ToTable("Favoriler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.IslemTipi", b =>
                {
                    b.Property<int>("IslemTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslemTipId"));

                    b.Property<string>("IslemTipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IslemTipId");

                    b.HasIndex("IslemTipAdi")
                        .IsUnique();

                    b.ToTable("IslemTipleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Kategori", b =>
                {
                    b.Property<int>("KategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KategoriId"));

                    b.Property<string>("KategoriAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("KategoriId");

                    b.HasIndex("KategoriAdi")
                        .IsUnique();

                    b.ToTable("Kategoriler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<bool>("OnlineMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("ProfilFotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("SonIpAdresi")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("DurumId");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.KullaniciRol", b =>
                {
                    b.Property<int>("KullaniciRolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciRolId"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("KullaniciRolId");

                    b.HasIndex("RolId");

                    b.HasIndex("KullaniciId", "RolId")
                        .IsUnique();

                    b.ToTable("KullaniciRolleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Kurs", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<int>("EgitmenId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KapakGorselUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KursAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("KursId");

                    b.HasIndex("DurumId");

                    b.HasIndex("EgitmenId");

                    b.ToTable("Kurslar", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.KursDegerlendirmesi", b =>
                {
                    b.Property<int>("DegerlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegerlendirmeId"));

                    b.Property<DateTime>("DegerlendirmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<byte>("Puan")
                        .HasColumnType("tinyint");

                    b.Property<string>("YorumMetni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegerlendirmeId");

                    b.HasIndex("KursId");

                    b.HasIndex("KullaniciId", "KursId")
                        .IsUnique();

                    b.ToTable("KursDegerlendirmeleri", null, t =>
                        {
                            t.HasCheckConstraint("CK_KursDegerlendirmeleri_Puan", "[Puan] BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("CoursVia.Models.KursKategorisi", b =>
                {
                    b.Property<int>("KursKategoriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursKategoriId"));

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.HasKey("KursKategoriId");

                    b.HasIndex("KategoriId");

                    b.HasIndex("KursId", "KategoriId")
                        .IsUnique();

                    b.ToTable("KursKategorileri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.KursKaydi", b =>
                {
                    b.Property<int>("KursKayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursKayitId"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("KayitTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TamamlanmaTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("KursKayitId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("KursId");

                    b.ToTable("KursKayitlari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.KursOnayi", b =>
                {
                    b.Property<int>("KursOnayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursOnayId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("DurumId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IslemTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.HasKey("KursOnayId");

                    b.HasIndex("AdminId");

                    b.HasIndex("DurumId");

                    b.HasIndex("KursId");

                    b.ToTable("KursOnaylari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.MateryalTipi", b =>
                {
                    b.Property<int>("MateryalTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MateryalTipId"));

                    b.Property<string>("MateryalTipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MateryalTipId");

                    b.HasIndex("MateryalTipAdi")
                        .IsUnique();

                    b.ToTable("MateryalTipleri", (string)null);

                    b.HasData(
                        new
                        {
                            MateryalTipId = 1,
                            MateryalTipAdi = "Doküman"
                        },
                        new
                        {
                            MateryalTipId = 2,
                            MateryalTipAdi = "Görsel"
                        },
                        new
                        {
                            MateryalTipId = 3,
                            MateryalTipAdi = "Ses"
                        },
                        new
                        {
                            MateryalTipId = 4,
                            MateryalTipAdi = "Video"
                        },
                        new
                        {
                            MateryalTipId = 5,
                            MateryalTipAdi = "Kod"
                        });
                });

            modelBuilder.Entity("CoursVia.Models.OgrenciCevabi", b =>
                {
                    b.Property<int>("OgrenciCevapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OgrenciCevapId"));

                    b.Property<bool>("DogruMu")
                        .HasColumnType("bit");

                    b.Property<int?>("SecenekId")
                        .HasColumnType("int");

                    b.Property<int>("SinavKatilimId")
                        .HasColumnType("int");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VerilmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("OgrenciCevapId");

                    b.HasIndex("SecenekId");

                    b.HasIndex("SoruId");

                    b.HasIndex("SinavKatilimId", "SoruId")
                        .IsUnique();

                    b.ToTable("OgrenciCevaplari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Oneri", b =>
                {
                    b.Property<int>("OneriId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OneriId"));

                    b.Property<bool>("GorulduMu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int?>("KursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("OneriMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OneriTipId")
                        .HasColumnType("int");

                    b.HasKey("OneriId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("KursId");

                    b.HasIndex("OneriTipId");

                    b.ToTable("Oneriler", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.OneriTipi", b =>
                {
                    b.Property<int>("OneriTipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OneriTipId"));

                    b.Property<string>("OneriTipAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OneriTipId");

                    b.HasIndex("OneriTipAdi")
                        .IsUnique();

                    b.ToTable("OneriTipleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("RolAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId");

                    b.HasIndex("RolAdi")
                        .IsUnique();

                    b.ToTable("Roller", (string)null);

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            RolAdi = "Admin"
                        },
                        new
                        {
                            RolId = 2,
                            RolAdi = "Eğitmen"
                        },
                        new
                        {
                            RolId = 3,
                            RolAdi = "Öğrenci"
                        });
                });

            modelBuilder.Entity("CoursVia.Models.Sertifika", b =>
                {
                    b.Property<int>("SertifikaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SertifikaId"));

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<string>("SertifikaKodu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("VerilmeTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("SertifikaId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("KursId");

                    b.HasIndex("SertifikaKodu")
                        .IsUnique();

                    b.ToTable("Sertifikalar", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.SifreSifirlama", b =>
                {
                    b.Property<int>("SifreSifirlamaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SifreSifirlamaId"));

                    b.Property<DateTime>("GecerlilikTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<bool>("KullanildiMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.HasKey("SifreSifirlamaId");

                    b.HasIndex("KullaniciId", "Kod");

                    b.ToTable("SifreSifirlamalari", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.Sinav", b =>
                {
                    b.Property<int>("SinavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavId"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GecmeNotu")
                        .HasColumnType("int");

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<string>("SinavAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("SoruSayisi")
                        .HasColumnType("int");

                    b.Property<int>("SureDakika")
                        .HasColumnType("int");

                    b.HasKey("SinavId");

                    b.HasIndex("KursId")
                        .IsUnique();

                    b.ToTable("Sinavlar", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sinavlar_GecmeNotu", "[GecmeNotu] BETWEEN 1 AND 100");

                            t.HasCheckConstraint("CK_Sinavlar_SoruSayisi", "[SoruSayisi] > 0");

                            t.HasCheckConstraint("CK_Sinavlar_SureDakika", "[SureDakika] > 0");
                        });
                });

            modelBuilder.Entity("CoursVia.Models.SinavKatilimi", b =>
                {
                    b.Property<int>("SinavKatilimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinavKatilimId"));

                    b.Property<int?>("AlinanPuan")
                        .HasColumnType("int");

                    b.Property<DateTime>("BaslamaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("SYSDATETIME()");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("GectiMi")
                        .HasColumnType("bit");

                    b.Property<int>("KursKayitId")
                        .HasColumnType("int");

                    b.Property<int>("SinavId")
                        .HasColumnType("int");

                    b.HasKey("SinavKatilimId");

                    b.HasIndex("KursKayitId");

                    b.HasIndex("SinavId");

                    b.ToTable("SinavKatilimlari", null, t =>
                        {
                            t.HasCheckConstraint("CK_SinavKatilimlari_AlinanPuan", "[AlinanPuan] IS NULL OR ([AlinanPuan] BETWEEN 0 AND 100)");
                        });
                });

            modelBuilder.Entity("CoursVia.Models.Soru", b =>
                {
                    b.Property<int>("SoruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoruId"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SinavId")
                        .HasColumnType("int");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SoruId");

                    b.HasIndex("SinavId");

                    b.ToTable("Sorular", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.SoruDersi", b =>
                {
                    b.Property<int>("SoruDersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoruDersId"));

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.HasKey("SoruDersId");

                    b.HasIndex("DersId");

                    b.HasIndex("SoruId", "DersId")
                        .IsUnique();

                    b.ToTable("SoruDersleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.SoruSecenegi", b =>
                {
                    b.Property<int>("SecenekId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecenekId"));

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("DogruMu")
                        .HasColumnType("bit");

                    b.Property<string>("SecenekMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.HasKey("SecenekId");

                    b.HasIndex("SoruId")
                        .IsUnique()
                        .HasDatabaseName("UX_SoruSecenekleri_TekDogru")
                        .HasFilter("[DogruMu] = 1 AND [AktifMi] = 1");

                    b.ToTable("SoruSecenekleri", (string)null);
                });

            modelBuilder.Entity("CoursVia.Models.AdminLog", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.IslemTipi", "IslemTipi")
                        .WithMany()
                        .HasForeignKey("IslemTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("IslemTipi");
                });

            modelBuilder.Entity("CoursVia.Models.Bildirim", b =>
                {
                    b.HasOne("CoursVia.Models.BildirimTipi", "BildirimTipi")
                        .WithMany()
                        .HasForeignKey("BildirimTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BildirimTipi");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("CoursVia.Models.Bolum", b =>
                {
                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany("Bolumler")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.Ders", b =>
                {
                    b.HasOne("CoursVia.Models.Bolum", "Bolum")
                        .WithMany("Dersler")
                        .HasForeignKey("BolumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany("Dersler")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bolum");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.DersIlerlemesi", b =>
                {
                    b.HasOne("CoursVia.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.KursKaydi", "KursKaydi")
                        .WithMany("DersIlerlemeleri")
                        .HasForeignKey("KursKayitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("KursKaydi");
                });

            modelBuilder.Entity("CoursVia.Models.DersMateryali", b =>
                {
                    b.HasOne("CoursVia.Models.Ders", "Ders")
                        .WithMany("DersMateryalleri")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.MateryalTipi", "MateryalTipi")
                        .WithMany()
                        .HasForeignKey("MateryalTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("MateryalTipi");
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenBransi", b =>
                {
                    b.HasOne("CoursVia.Models.EgitmenProfili", "EgitmenProfili")
                        .WithMany("EgitmenBranslari")
                        .HasForeignKey("EgitmenProfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kategori", "Kategori")
                        .WithMany("EgitmenBranslari")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EgitmenProfili");

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenOnayi", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenProfili", b =>
                {
                    b.HasOne("CoursVia.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithOne("EgitmenProfili")
                        .HasForeignKey("CoursVia.Models.EgitmenProfili", "KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("CoursVia.Models.Favori", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.Kullanici", b =>
                {
                    b.HasOne("CoursVia.Models.Durum", "Durum")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");
                });

            modelBuilder.Entity("CoursVia.Models.KullaniciRol", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Rol", "Rol")
                        .WithMany("KullaniciRolleri")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CoursVia.Models.Kurs", b =>
                {
                    b.HasOne("CoursVia.Models.Durum", "Durum")
                        .WithMany("Kurslar")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kullanici", "Egitmen")
                        .WithMany("EgitmenKurslari")
                        .HasForeignKey("EgitmenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Durum");

                    b.Navigation("Egitmen");
                });

            modelBuilder.Entity("CoursVia.Models.KursDegerlendirmesi", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany("KursDegerlendirmeleri")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.KursKategorisi", b =>
                {
                    b.HasOne("CoursVia.Models.Kategori", "Kategori")
                        .WithMany("KursKategorileri")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany("KursKategorileri")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.KursKaydi", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany("KursKayitlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.KursOnayi", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Durum", "Durum")
                        .WithMany()
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Durum");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.OgrenciCevabi", b =>
                {
                    b.HasOne("CoursVia.Models.SoruSecenegi", "SoruSecenegi")
                        .WithMany()
                        .HasForeignKey("SecenekId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoursVia.Models.SinavKatilimi", "SinavKatilimi")
                        .WithMany("OgrenciCevaplari")
                        .HasForeignKey("SinavKatilimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SinavKatilimi");

                    b.Navigation("Soru");

                    b.Navigation("SoruSecenegi");
                });

            modelBuilder.Entity("CoursVia.Models.Oneri", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CoursVia.Models.OneriTipi", "OneriTipi")
                        .WithMany()
                        .HasForeignKey("OneriTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kurs");

                    b.Navigation("OneriTipi");
                });

            modelBuilder.Entity("CoursVia.Models.Sertifika", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.SifreSifirlama", b =>
                {
                    b.HasOne("CoursVia.Models.Kullanici", "Kullanici")
                        .WithMany("SifreSifirlamalari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("CoursVia.Models.Sinav", b =>
                {
                    b.HasOne("CoursVia.Models.Kurs", "Kurs")
                        .WithOne("Sinav")
                        .HasForeignKey("CoursVia.Models.Sinav", "KursId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kurs");
                });

            modelBuilder.Entity("CoursVia.Models.SinavKatilimi", b =>
                {
                    b.HasOne("CoursVia.Models.KursKaydi", "KursKaydi")
                        .WithMany()
                        .HasForeignKey("KursKayitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Sinav", "Sinav")
                        .WithMany("SinavKatilimlari")
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KursKaydi");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("CoursVia.Models.Soru", b =>
                {
                    b.HasOne("CoursVia.Models.Sinav", "Sinav")
                        .WithMany("Sorular")
                        .HasForeignKey("SinavId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("CoursVia.Models.SoruDersi", b =>
                {
                    b.HasOne("CoursVia.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoursVia.Models.Soru", "Soru")
                        .WithMany("SoruDersleri")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("CoursVia.Models.SoruSecenegi", b =>
                {
                    b.HasOne("CoursVia.Models.Soru", "Soru")
                        .WithMany("SoruSecenekleri")
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("CoursVia.Models.Bolum", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("CoursVia.Models.Ders", b =>
                {
                    b.Navigation("DersMateryalleri");
                });

            modelBuilder.Entity("CoursVia.Models.Durum", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("Kurslar");
                });

            modelBuilder.Entity("CoursVia.Models.EgitmenProfili", b =>
                {
                    b.Navigation("EgitmenBranslari");
                });

            modelBuilder.Entity("CoursVia.Models.Kategori", b =>
                {
                    b.Navigation("EgitmenBranslari");

                    b.Navigation("KursKategorileri");
                });

            modelBuilder.Entity("CoursVia.Models.Kullanici", b =>
                {
                    b.Navigation("EgitmenKurslari");

                    b.Navigation("EgitmenProfili");

                    b.Navigation("KullaniciRolleri");

                    b.Navigation("KursKayitlari");

                    b.Navigation("SifreSifirlamalari");
                });

            modelBuilder.Entity("CoursVia.Models.Kurs", b =>
                {
                    b.Navigation("Bolumler");

                    b.Navigation("Dersler");

                    b.Navigation("KursDegerlendirmeleri");

                    b.Navigation("KursKategorileri");

                    b.Navigation("Sinav");
                });

            modelBuilder.Entity("CoursVia.Models.KursKaydi", b =>
                {
                    b.Navigation("DersIlerlemeleri");
                });

            modelBuilder.Entity("CoursVia.Models.Rol", b =>
                {
                    b.Navigation("KullaniciRolleri");
                });

            modelBuilder.Entity("CoursVia.Models.Sinav", b =>
                {
                    b.Navigation("SinavKatilimlari");

                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("CoursVia.Models.SinavKatilimi", b =>
                {
                    b.Navigation("OgrenciCevaplari");
                });

            modelBuilder.Entity("CoursVia.Models.Soru", b =>
                {
                    b.Navigation("SoruDersleri");

                    b.Navigation("SoruSecenekleri");
                });
#pragma warning restore 612, 618
        }
    }
}
